# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    connection-timeout: 5000

spring:
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    devtools:
        restart:
          enabled: false
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/app?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#    http:
#        multipart:
#            max-file-size: 100MB
#            max-request-size: 100MB
#            enabled: true
#    resources: # 指定静态资源的路径
#        static-locations: classpath:/static/
#    redis:
#        open: true  # 是否开启redis缓存  true开启   false关闭
#        database: 0
#        host: 58.213.91.96   #dev
#        port: 29012
#        password:       # 密码（默认为空）
#        timeout: 6000  # 连接超时时长（毫秒）
#        pool:
#            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#            max-idle: 10      # 连接池中的最大空闲连接
#            min-idle: 5       # 连接池中的最小空闲连接


# Mybatis配置
#mybatis:
#    mapper-locations: classpath:mapper/*.xml
#    configuration:
#        map-underscore-to-camel-case: true

# mybatis-plus配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  #mapper-locations: classpath:/com/example/demo/mapper/*/*.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.qiwei.smsverify.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    meta-object-handler: com.qiwei.smsverify.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true